### ISSUE TITLE
Encountering assertion error

### ISSUE THREAD

**Issue by sagnikbanerjee15** [rcanovas/libCSAM#2] opened 2021-10-19 12:49 UTC
Hello,

I am encountering the following error while running DecompressSAM on a file that was compressed using CompressSAM

```
DecompressSAM: src/cqual/././../basics/./io.h:79: T cds::basic::LoadValue(std::istream&) [with T = long unsigned int; std::istream = std::basic_istream<char>]: Assertion `in.good()' failed.
Aborted (core dumped)
```

I had compressed another SAM file the exact same way and the decompression had worked for it. 
Could you please look into this?

Thank you.

**Comment by rcanovas** [comment] 2021-10-20 01:00
Hello,

Sadly the code has not been updated since 2015, so probably the problem is how many bits variables as long unsigned int used on the machine where the data was compressed, and how many bits are assigned to this variables in the machine where you are trying to decompressed. It is difficult to know with out having access to the file. Do you have a link to a compressed file where you have find this issue, so I can verify the problem?

**Comment by sagnikbanerjee15** [comment] 2021-10-20 17:15
Here is the link to one of the files. Please let me know if you have any issues accessing it.

https://drive.google.com/file/d/1Lbf_7gONFDUKejXZT_Q_3oZ9ZluysAYr/view?usp=sharing

Thank you.

**Comment by rcanovas** [comment] 2021-10-21 01:26
![Screenshot from 2021-10-21 12-21-00](https://user-images.githubusercontent.com/791596/138195074-f6b48353-6ffa-409b-8d8c-1a20841a603c.png)

I downloaded the csam.zip  file that you send me (and unzipped) and the current version of the libCSAM and the decompression finished without any problem. So, not sure what is the problem here.

**Comment by sagnikbanerjee15** [comment] 2021-10-29 15:03
Thanks for your help. It seems like I was running several jobs at once and it ran out of memory. Its fixed now.

**Closed as completed** 2021-10-30 00:58 UTC
